/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ArgoCdWhereInput } from "./ArgoCdWhereInput";
import { Type } from "class-transformer";
import { ArgoCdOrderByInput } from "./ArgoCdOrderByInput";

@ArgsType()
class ArgoCdFindManyArgs {
  @ApiProperty({
    required: false,
    type: () => ArgoCdWhereInput,
  })
  @Field(() => ArgoCdWhereInput, { nullable: true })
  @Type(() => ArgoCdWhereInput)
  where?: ArgoCdWhereInput;

  @ApiProperty({
    required: false,
    type: ArgoCdOrderByInput,
  })
  @Field(() => ArgoCdOrderByInput, { nullable: true })
  @Type(() => ArgoCdOrderByInput)
  orderBy?: ArgoCdOrderByInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { ArgoCdFindManyArgs };
