/*
//------------------------------------------------------------------------------ 
// This code was generated by Amplication. 
// 
// Changes to this file will be lost if the code is regenerated. 
//
// There are other ways to to customize your code, see this doc to learn more
// https://docs.amplication.com/docs/how-to/custom-code
//
//------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import * as gqlUserRoles from "../../auth/gqlUserRoles.decorator";
import * as abacUtil from "../../auth/abac.util";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { CreateArgoCdArgs } from "./CreateArgoCdArgs";
import { UpdateArgoCdArgs } from "./UpdateArgoCdArgs";
import { DeleteArgoCdArgs } from "./DeleteArgoCdArgs";
import { ArgoCdFindManyArgs } from "./ArgoCdFindManyArgs";
import { ArgoCdFindUniqueArgs } from "./ArgoCdFindUniqueArgs";
import { ArgoCd } from "./ArgoCd";
import { User } from "../../user/base/User";
import { ArgoCdService } from "../argoCd.service";

@graphql.Resolver(() => ArgoCd)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class ArgoCdResolverBase {
  constructor(
    protected readonly service: ArgoCdService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ArgoCd",
    action: "read",
    possession: "any",
  })
  async _argoCdsMeta(
    @graphql.Args() args: ArgoCdFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @graphql.Query(() => [ArgoCd])
  @nestAccessControl.UseRoles({
    resource: "ArgoCd",
    action: "read",
    possession: "any",
  })
  async argoCds(
    @graphql.Args() args: ArgoCdFindManyArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ArgoCd[]> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "ArgoCd",
    });
    const results = await this.service.findMany(args);
    return results.map((result) => permission.filter(result));
  }

  @graphql.Query(() => ArgoCd, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ArgoCd",
    action: "read",
    possession: "own",
  })
  async argoCd(
    @graphql.Args() args: ArgoCdFindUniqueArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ArgoCd | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "own",
      resource: "ArgoCd",
    });
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return permission.filter(result);
  }

  @graphql.Mutation(() => ArgoCd)
  @nestAccessControl.UseRoles({
    resource: "ArgoCd",
    action: "create",
    possession: "any",
  })
  async createArgoCd(
    @graphql.Args() args: CreateArgoCdArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ArgoCd> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "create",
      possession: "any",
      resource: "ArgoCd",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ArgoCd"} creation is forbidden for roles: ${roles}`
      );
    }
    // @ts-ignore
    return await this.service.create({
      ...args,
      data: {
        ...args.data,

        userId: {
          connect: args.data.userId,
        },
      },
    });
  }

  @graphql.Mutation(() => ArgoCd)
  @nestAccessControl.UseRoles({
    resource: "ArgoCd",
    action: "update",
    possession: "any",
  })
  async updateArgoCd(
    @graphql.Args() args: UpdateArgoCdArgs,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<ArgoCd | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "update",
      possession: "any",
      resource: "ArgoCd",
    });
    const invalidAttributes = abacUtil.getInvalidAttributes(
      permission,
      args.data
    );
    if (invalidAttributes.length) {
      const properties = invalidAttributes
        .map((attribute: string) => JSON.stringify(attribute))
        .join(", ");
      const roles = userRoles
        .map((role: string) => JSON.stringify(role))
        .join(",");
      throw new apollo.ApolloError(
        `providing the properties: ${properties} on ${"ArgoCd"} update is forbidden for roles: ${roles}`
      );
    }
    try {
      // @ts-ignore
      return await this.service.update({
        ...args,
        data: {
          ...args.data,

          userId: {
            connect: args.data.userId,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ArgoCd)
  @nestAccessControl.UseRoles({
    resource: "ArgoCd",
    action: "delete",
    possession: "any",
  })
  async deleteArgoCd(
    @graphql.Args() args: DeleteArgoCdArgs
  ): Promise<ArgoCd | null> {
    try {
      // @ts-ignore
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ArgoCd",
    action: "read",
    possession: "any",
  })
  async userId(
    @graphql.Parent() parent: ArgoCd,
    @gqlUserRoles.UserRoles() userRoles: string[]
  ): Promise<User | null> {
    const permission = this.rolesBuilder.permission({
      role: userRoles,
      action: "read",
      possession: "any",
      resource: "User",
    });
    const result = await this.service.getUserId(parent.id);

    if (!result) {
      return null;
    }
    return permission.filter(result);
  }
}
